### ISSUE TITLE
Bundle issues?

### ISSUE THREAD

**Issue by mikestopcontinues** [jhonnymichel/react-hookstore#11]
I'm getting two errors that I suspect points to an issue with bundling in this lib.

The first is that the following line causes an issue with `eslint-plugin-import`'s rule `import/no-unresolved`, even though it actually works fine:

```js
import {createStore, useStore} from 'react-hookstore';
```

But I don't think the plugin is in error, because the webpack plugin `CaseSensitivePathsPlugin` issues the following warning:

```
Module not found: [CaseSensitivePathsPlugin] `MY_PROJECT/node_modules/React/index.js` 
does not match the corresponding path on disk `react`.
```

I looked into the source, but I'm at a loss for what's going on.

**Comment by jhonnymichel** [comment]
Hi @mikestopcontinues . Could you provide your exact bundle setup so I can troubleshoot what is causing incompatibility from our side? thanks

**Comment by mikestopcontinues** [comment]
Sorry for the delay. I'll put a minimum config together when I get home on
Monday.

>

**Comment by mikestopcontinues** [comment]
I was able to reproduce the eslint issue, but I'm having a harder time untangling the webpack issue from the library's (react-static's) config.

Here's the eslint issue: 
https://github.com/mikestopcontinues/hookstore-issue

**Comment by jhonnymichel** [comment]
@mikestopcontinues sorry for the delay, didn't have time at all to check on this. Will do it this weekend
