### ISSUE TITLE
Fantastic implementation 🎉

### ISSUE THREAD

**Issue by asbjornenge** [jhonnymichel/react-hookstore#13]
Hi friend!

I just wanted to reach out and thank you for a fantastic "shared state mgmt" solution for hooks 🙌🌈🚀

I've been researching hooks this weekend and was unhappy with the complexity of other solutions out there. I started building my own with the same idea you have implemented here. I almost had it when I stumbled across your lib here that just hit the nail 🔨 Neatly laid out in > 100 loc 👌

Fantastic work 🎉 Keep it up!
(feel free to close the issue when you have read it 😉)

**Comment by jhonnymichel** [comment]
Wow! I'm pleased by your words. Thanks for being kind. Good to now you enjoyed the implementation and made use of it!
