### ISSUE TITLE
server side rendering support?

### ISSUE THREAD

**Issue by pencilcheck** [jhonnymichel/react-hookstore#14]
Getting errors such as `ReferenceError: window is not defined` when running with nextjs with ssr enabled, is there a way to get around it?

Btw, the "window" usage seems to be added by webpack, a simple tweak of webpack config should be able to eliminate that.

**Comment by jhonnymichel** [comment]
@pencilcheck good catch, I'll fix this tomorrow, hope you're not getting too let down by it

**Comment by pencilcheck** [comment]
Nah it’s ok. I just copied the file and use it as a local lib for now which is not ideal but it works until you fix it.

**Comment by jhonnymichel** [comment]
@pencilcheck just updated the lib and version 1.2.1 solves the window is not defined error. Would you try it out?

**Comment by pencilcheck** [comment]
Wow, thanks for update. It worked.
