### ISSUE TITLE
cannot use useStore outside React Components

### ISSUE THREAD

**Issue by thainq3127** [jhonnymichel/react-hookstore#16]
I'm new to ReactJS, so i'm into with hook API. But with this, i cannot call useStore outside React components to use dispatch or setState, as I saw from other redux example, they are able to use dispatch inside other reducer. Do you have any solution than pass dispatch around inside action.payload?

**Comment by jhonnymichel** [comment]
Hey, thats just how hooks are supposed to work.

Do not use `useStore` outside components. use the store object directly. 

Check this example and let me know if you understand https://github.com/jhonnymichel/react-hookstore/issues/4

**Comment by thainq3127** [comment]
Yeah, i got it now, i was just too confuse with () => dispatch => return dispatch(). Thank you
