### ISSUE TITLE
What about implementing a reducer logger?

### ISSUE THREAD

**Issue by DavoBR** [jhonnymichel/react-hookstore#18]
I've been looking for an easy way to implement React-Hooks without reinventing the wheel and I found this library, but like Redux has a logger, do you plan to implement your own logger? Or is there a way to implement [use-reducer-logger](https://github.com/jefflombard/use-reducer-logger)? something like middlewares

**Comment by jhonnymichel** [comment]
It would be easy enough to create a high-order-reducer that adds the log functionality on the app code. I currently have no plans on adding support to middlewares

**Comment by jhonnymichel** [comment]
I think this use-reducer-logger might work, it is exactly a high-order-reducer
