### ISSUE TITLE
Non-breaking typo, subsriberExists -> subscriberExists

### ISSUE THREAD

**Issue by kfwebdev** [jhonnymichel/react-hookstore#23]
https://github.com/jhonnymichel/react-hookstore/blob/e6a48a5d315d285a1bc161bc57d5925e75bf680d/src/index.js#L140

Just noticed this while reviewing the code. It doesn't affect anything but just thought I would mention it. Looking to use your library because of it's nice concise approach! :+1:

**Comment by jhonnymichel** [comment]
Hey thanks! I will resolve all the issues this week

**Comment by kfwebdev** [comment]
No problem, thanks for contributing this useful library!
